#!/usr/bin/env bash

# Shorthand for invoking the assembler CLI.
# 
# Expects the name of a file in ../programs/asm/ (though this can include
# subdirectories). It calls the assembler and emits a binary file 
# in ../programs/bin/. 
# 
# Extra arguments to this script will be passed along to the assembler.

# check correct number of arguments
if [ ! "$#" -ge 1 ]; then
    echo "usage: assemble FILENAME [EXTRA_ARGS ...]"
    exit -1
fi

FILENAME=$1
EXTRA_ARGS=${@:2} # rest of arguments

# use the default locations for asm files
ASM_PATH=../programs/asm/$FILENAME.3000.s

# put binaries in bin/ regardless of if they were in subdirs of asm/
FILE_BASENAME=$(basename $FILENAME)
BIN_PATH=../programs/bin/$FILE_BASENAME.3000.b

# ensure source file exists
if [ ! -f "$ASM_PATH" ]; then
    echo "$ASM_PATH does not exist."
    exit -1
fi

echo "Assembling $FILENAME.3000.s to $FILE_BASENAME.3000.b"
dune exec bin/assemble.exe $ASM_PATH $BIN_PATH -- $EXTRA_ARGS
